name: flutter_magnifier
description: A Flutter package that provides a magnifying glass effect for any widget.
version: 0.0.2
homepage: https://github.com/gokalpyildiz/flutter_magnifier
repository: https://github.com/gokalpyildiz/flutter_magnifier
issue_tracker: https://github.com/gokalpyildiz/flutter_magnifier/issues

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

